spring.application.name=doc-auditor-service
# Database Connection - Use 127.0.0.1 to avoid Windows localhost lag
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/auditor_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP (Connection Pool) Patience
# This prevents the app from crashing if the DB takes 10 seconds to wake up
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=45000
spring.datasource.hikari.maximum-pool-size=10

# Vector Store Initialization
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.table-name=vector_store


# CRITICAL: Match this to nomic-embed-text (Ollama)
spring.ai.vectorstore.pgvector.dimensions=768

# Ollama Configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=ictrek/llama3.2:3b
spring.ai.ollama.embedding.options.model=nomic-embed-text